### ISSUE TITLE
header information already sent in enqueue-scripts.php (line 145) 

### ISSUE THREAD

**Issue by Aheleos** [erikyo/modul-r#6]
It looks like wordpress kicks back a warning because modul-r is sending info before the before wordpress admin tries. The warning appears when logged in as admin and editing a page. I am going to look at solving this this week when I have time, but would certainly welcome someone else getting to it first :) Here is the complete error without the full path from my local drive 

Warning: Cannot modify header information - headers already sent by (output started at [...]\themes]modul-r\inc\enqueue-scripts.php:145) in [...]\wp-admin\admin\admin-header.php on line 9

**Comment by erikyo** [comment]
ok thanks! I'll take a look

**Comment by erikyo** [comment]
OK I fixed the problem! I think Gutenberg in a new update already adds custom colors and this function isn't needed anymore, so I removed it!

**Comment by Aheleos** [comment]
That's awesome. Thank you so much for fixing it quickly.
